#!/bin/bash

# Install Prometheus Node Exporter

wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
tar xvzf node_exporter-1.5.0.linux-amd64.tar.gz
sudo cp node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin
sudo useradd -rs /bin/false node_exporter
sudo mkdir /etc/node_exporter

sudo cat << 'EOF' > /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter
After=network.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter --web.config.file=/etc/node_exporter/configuration.yaml

[Install]
WantedBy=multi-user.target
EOF

sudo cat << EOF >> /etc/node_exporter/configuration.yaml
basic_auth_users:
  prometheus: \$2y\$10\$5DLwE/5zYr8Irryew17ZZeVsGNUk7CxyvzyL16LdOvtJLKNIage9C

EOF

sudo chmod 700 /etc/node_exporter
sudo chmod 600 /etc/node_exporter/*
sudo chown -R node_exporter:node_exporter /etc/node_exporter

sudo systemctl daemon-reload
sudo systemctl enable node_exporter
sudo systemctl start node_exporter